apps/adopcion/urls.py
from django.conf.urls import url

from apps.adopcion.views import index_adopcion
urlpatterns = [
    url(r'^$', index_adopcion), 
]

apps/mascota/urls.py
from django.conf.urls import url,include

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete
urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^nuevo$', mascota_view, name="mascota_view"),
    url(r'^listar$', mascota_list, name="mascota_listar"),
    url(r'^editar/(?P<id_mascota>\d+)/$', mascota_edit, name="mascota_editar"),
    url(r'^eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name="mascota_eliminar"),
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace='mascota')),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace='adopcion')),
]

apps/adopcion/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=70)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=12)
	email = models.EmailField()
	domicilio = models.TextField()

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellidos)

apps/mascota/models.py
from django.db import models

from apps.adopcion.models import Persona

# Create your models here.

class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)
	def __str__(self):
		return '{}'.format(self.nombre)

class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	sexo =  models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna, blank=True)

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota

		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]
		labels = {
			'nombre' : 'Nombre',
			'sexo' : 'Sexo',
			'edad_aproximada' : 'Edad Aprximada',
			'fecha_rescate' : 'Fecha de Rescate',
			'persona' : 'Adoptante',
			'vacuna' : 'Vacunas',
		}
		widgets = {
			'nombre' : forms.TextInput(attrs={'class':'form-control'}),
			'sexo' : forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada' : forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate' : forms.TextInput(attrs={'class':'form-control'}),
			'persona' : forms.Select(attrs={'class':'form-control'}),
			'vacuna' : forms.CheckboxSelectMultiple(),
		}
		

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index_adopcion(response):
	return HttpResponse("Soy la pagina principal de la app adopcion")

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from apps.mascota.forms import MascotaForm

from apps.mascota.models import Mascota

# Create your views here.

def index(request):
	return render(request, 'mascota/index.html')

def mascota_view(request):

	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:index')
	else:
		form = MascotaForm()
	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id')
	contexto = {'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == "GET":
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	{% block extrastatic %}
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	{% endblock %}

	<meta charset="UTF-8">
	<title>{% block title%} Document {% endblock %}</title>
</head>
<body>
	{% block navbar%}
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="#">Brand</a>
			    </div>
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			    	<ul class="nav navbar-nav">
				        <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mascota <span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><a href="{% url 'mascota:mascota_view' %}">Registrar</a></li>
				            <li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
				          </ul>
				        </li>
				        <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Adopciones <span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><a href="#">Solicitar</a></li>
				            <li><a href="#">Listar Solicitudes</a></li>
				          </ul>
				        </li>
				      </ul>
				      <ul class="nav navbar-nav navbar-right">
				        <li><a href="#">Codigo Facilito</a></li>
				        <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Opciones <span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><a href="#">Salir</a></li>
				          </ul>
				        </li>
				      </ul>
			    </div>
			</div>
		</nav>	
	{% endblock %}

	{% block content %}
		<h5>Este es el contenido del archivo base</h5>
	{% endblock %}

	{% block extrajs %}
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script>
			
		</script>
	{% endblock %}
	<!--
		Mascotas
			Registrar
			Lisar
		Adopciones
			Solicitar
			Listar Solicitudes
		Codigo Facilito
		Opciones
	-->
</body>
</html>

templates/mascota/index.html
{% extends 'base/base.html' %}


{% block content %}
<h5>soy el contenido de mascota</h5>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
	<form method="post" class="form-horizontal">
		{% csrf_token %}
		<h3>¿Desea eliminar el registro {{ mascota.nombre }}?</h3>
		<button class="btn btn-danger" type="submit">Si, eliminar</button>
		<a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
	</form>
</div>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
	<form method="post" class="form-horizontal">
		{% csrf_token %}
		{{form.as_p}}
		<div class="row centered">
			<input type="submit" class="btn btn-success" value="Ingresar">
		</div>
	</form>
</div>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content%}
	<div class="container">
		<table class="table table-bordered">
			<thead>
				<tr>
					<td>#</td>
					<td>Nombre</td>
					<td>Sexo</td>
					<td>Edad</td>
					<td>Fecha de Rescate</td>
					<td>Adoptante</td>
					<td>Acciones</td>
				</tr>
			</thead>
			<tbody>
				{% if mascotas %}
					{% for mascota in mascotas %}
						<tr>
							<td>{{ mascota.id}}</td>
							<td>{{ mascota.nombre}}</td>
							<td>{{ mascota.sexo}}</td>
							<td>{{ mascota.edad_aproximada}}</td>
							<td>{{ mascota.fecha_rescate}}</td>
							<td>{{ mascota.persona.nombre}} {{ mascota.persona.apellidos }}</td>
							<td>
								<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
								<a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
							</td>
						</tr>
					{% endfor %}
				{% else%}
					<h1>No hay Registro de Mascotas</h1>
				{% endif%}
			</tbody>
		</table>
	</div>
{% endblock %}
<!--
	2000 de concentrado
	2 panes de 200
	2 colcafe
	2000 de aceite
-->